### ISSUE TITLE
Get 22A9 of GeoSupport into Docker.

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/docker-geosupport#19]
The [GitHub Action](https://github.com/NYCPlanning/docker-geosupport/actions) stopped running automatically.  The goal is to update [docker-geosupport](https://hub.docker.com/r/nycplanning/docker-geosupport/tags) with Geosupport version 22A9, which is 22.1.9, with 9 being the version of [UPAD](https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-gde-home.page).  Unfortunately, the action fails when run manually.  I think this is because the action is looking for version 22.1.2 ( by adding 1 to the current minor), but 22.1.2 is no longer available on Bytes.  I think the way to fix this to get this going again to to set the minor to `9` temporally [here](https://github.com/NYCPlanning/docker-geosupport/blob/6689e0bedf70b4eb20d85188d8fc108a89de3798/versions.py), and run the action to get the latest version.  Then remove the temporary hard coded value, and things should then work as expected with the automated runs. 

I'd like someone else's input on this before making any changes.

**Comment by td928** [comment]
this is fixed with a [one off feature branch](https://github.com/NYCPlanning/docker-geosupport/compare/main...19-get-upad9). Since the issue with this particular patch number is that it is on top of another patched version geosupport 22a2 which causes some of the urls incompatible with the existing workflow. But this should revert back to normal after this version 22a9.
